"""create book table

Revision ID: 60aef1f7a6b0
Revises: 
Create Date: 2025-11-23 23:22:26.612460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60aef1f7a6b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('employees')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('emp_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('lname', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('dept', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('salary', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('30000.00'), autoincrement=False, nullable=True),
    sa.Column('hire_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('emp_id', name=op.f('employees_pkey')),
    sa.UniqueConstraint('email', name=op.f('employees_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
